version: '3.2'

services:
  web:
    image: bj_admin_core
    container_name: bj_admin_core
    networks:
      backend:
        aliases:
          - bj_admin_core
    restart: always
    ports:
      - 7780:80
    build:
      context: ./docker/web/
      dockerfile: Dockerfile

networks:
  backend:
    driver: bridge
